export const routes = {
  root: "/",
  login: "/session/new",
  session: "/session",          // POST: create | DELETE: destroy
  register: "/registration/new",
  registration: "/registration",
  forgotPassword: "/passwords/new",
  passwords: "/passwords",
  password: (token: string) => `/passwords/${token}`,
  profile: "/profile",
  editProfile: "/profile/edit",
  requests: "/requests",
  newRequest: "/requests/new",
  request: (id: number) => `/requests/${id}`,
  confirmPayment: (id: number) => `/requests/${id}/confirm_payment`,
  downloadDocument: (id: number, docId: number) =>
    `/requests/${id}/download_document?document_id=${docId}`,
  requestMessages: (id: number) => `/requests/${id}/messages`,
  conversations: "/conversations",
  conversation: (id: number) => `/conversations/${id}`,
  conversationMessages: (id: number) => `/conversations/${id}/messages`,
  inbox: "/inbox",
  inboxConversation: (id: number) => `/inbox/${id}`,
  teachers: "/teachers",
  assignStudent: (id: number) => `/teachers/${id}/assign_student`,
  removeStudent: (id: number) => `/teachers/${id}/remove_student`,
  lessons: "/lessons",
  lesson: (id: number) => `/lessons/${id}`,
  notifications: "/notifications",
  markAllRead: "/notifications/mark_all_read",
  privacyPolicy: "/privacy-policy",
  admin: {
    root: "/admin",
    users: "/admin/users",
    newUser: "/admin/users/new",
    user: (id: number) => `/admin/users/${id}`,
    editUser: (id: number) => `/admin/users/${id}/edit`,
    assignRole: (id: number) => `/admin/users/${id}/assign_role`,
    removeRole: (id: number) => `/admin/users/${id}/remove_role`,
    lessons: "/admin/lessons",
  },
}
