export function publicRoute(page: string, locale: string): string {
  return page === "" ? `/${locale}` : `/${locale}/${page}`
}

export const publicPages = {
  home: "",
  homologacion: "homologation",
  universidad: "university",
  espanol: "spanish",
  consulta: "consultation",
  precios: "pricing",
  consultationThankYou: "consultation-thank-you",
} as const

export const routes = {
  dashboard: "/dashboard",
  login: "/session/new",
  session: "/session",          // POST: create | DELETE: destroy
  register: "/registration/new",
  registration: "/registration",
  forgotPassword: "/passwords/new",
  passwords: "/passwords",
  password: (token: string) => `/passwords/${token}`,
  profile: "/profile",
  editProfile: "/profile/edit",
  connectTelegram: "/profile/connect_telegram",
  disconnectTelegram: "/profile/disconnect_telegram",
  settings: {
    root: "/settings",
    profile: "/settings/profile",
    account: "/settings/account",
    notifications: "/settings/notifications",
    requestDeletion: "/settings/request_deletion",
    connectTelegram: "/settings/connect_telegram",
    disconnectTelegram: "/settings/disconnect_telegram",
  },
  requests: "/requests",
  newRequest: "/requests/new",
  request: (id: number) => `/requests/${id}`,
  confirmPayment: (id: number) => `/requests/${id}/confirm_payment`,
  createCheckoutSession: (id: number) => `/requests/${id}/create_checkout_session`,
  retrySync: (id: number) => `/requests/${id}/retry_sync`,
  downloadDocument: (id: number, docId: number) =>
    `/requests/${id}/download_document?document_id=${docId}`,
  requestMessages: (id: number) => `/requests/${id}/messages`,
  conversations: "/conversations",
  conversation: (id: number) => `/conversations/${id}`,
  conversationMessages: (id: number) => `/conversations/${id}/messages`,
  chats: "/chats",
  chat: (id: number) => `/chats/${id}`,
  teachers: "/teachers",
  teacher: (id: number) => `/teachers/${id}`,
  assignStudent: (id: number) => `/teachers/${id}/assign_student`,
  removeStudent: (id: number) => `/teachers/${id}/remove_student`,
  lessons: "/lessons",
  lesson: (id: number) => `/lessons/${id}`,
  notifications: "/notifications",
  notification: (id: number) => `/notifications/${id}`,
  markAllRead: "/notifications/mark_all_read",
  privacyPolicy: "/privacy-policy",
  admin: {
    root: "/admin",
    users: "/admin/users",
    newUser: "/admin/users/new",
    user: (id: number) => `/admin/users/${id}`,
    editUser: (id: number) => `/admin/users/${id}/edit`,
    assignRole: (id: number) => `/admin/users/${id}/assign_role`,
    removeRole: (id: number) => `/admin/users/${id}/remove_role`,
    gdprDelete: (id: number) => `/admin/users/${id}/gdpr_delete`,
    lessons: "/admin/lessons",
    pipeline: "/admin/pipeline",
    pipelineUpdate: (id: number) => `/admin/pipeline/${id}`,
    pipelineAdvance: (id: number) => `/admin/pipeline/${id}/advance`,
    pipelineRetreat: (id: number) => `/admin/pipeline/${id}/retreat`,
  },
}
